export const GET_CONTACTS = "GET_CONTACTS";
export const GET_CONTACTS_SUCCESS = "GET_CONTACTS_SUCCESS";
export const GET_CONTACTS_FAILURE = "GET_CONTACTS_FAILURE";
export const RESET_CONTACTS = "RESET_CONTACTS";

export const UPDATE_SEARCH_KEYWORD = "UPDATE_SEARCH_KEYWORD";
export const UPDATE_ONLY_EVEN_FILTER = "UPDATE_ONLY_EVEN_FILTER";
export const UPDATE_PAGE_NO = "UPDATE_PAGE_NO";
export const INCREMENT_PAGE_NO = "INCREMENT_PAGE_NO";
export const UPDATE_COUNTRY = "UPDATE_COUNTRY";

export const AUTH_TOKEN =
  "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjU2MCwiZXhwIjoxNzI2NTY3MTc5LCJ0eXBlIjoiYWNjZXNzIiwidGltZXN0YW1wIjoxNjk1MDMxMTc5fQ.0y7NtuVDCvcPvmWbliMs1q02sov2oFC6u2Hi6H4A2W4";
export const DEFAULT_COMPANY_ID = 171;

export const COUNTRY_ALL = 0;
export const COUNTRY_US = 226;
